//! Progression system integration for the simulation kernel.
//!
//! Handles XP awarding, level-up processing, skill point spending,
//! Mark assignment, and deriving combat bonuses from skill levels.

#![forbid(unsafe_code)]

use std::collections::{BTreeMap, BTreeSet};

use pb_core::event::Event;
use pb_core::ids::ActorId;
use pb_core::progression::{
    check_level_up, level_grants_mark, marks_earned_by_level, xp_for_level, SkillLine,
    BASE_SCENARIO_XP, BONUS_OBJECTIVE_XP, HEADSHOT_BONUS_XP, NO_CASUALTIES_BONUS_XP,
    OBJECTIVE_BONUS_XP, SKILL_POINTS_PER_LEVEL,
};

/// Per-actor progression data tracked within the simulation.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ActorProgression {
    /// Total experience points earned.
    pub xp: u64,
    /// Current character level (starts at 1).
    pub level: u32,
    /// Unspent skill points.
    pub skill_points: u32,
    /// Skill level per skill line (0 = untrained, max 10).
    pub skill_levels: BTreeMap<SkillLine, u32>,
    /// Mark (perk) string IDs that this actor has acquired.
    pub marks: Vec<String>,
    /// Way (trait) string ID chosen at creation, if any.
    pub way: Option<String>,
    /// Data-authored passive effect identifiers resolved by the content layer.
    #[serde(default)]
    pub passives: BTreeSet<String>,
    /// Data-authored active ability identifiers resolved by the content layer.
    #[serde(default)]
    pub abilities: BTreeSet<String>,
    /// Numeric effect values by stable semantic key.
    #[serde(default)]
    pub effect_values: BTreeMap<String, i32>,
}

impl ActorProgression {
    /// Create a new progression state for a brand-new character (level 1, no XP).
    pub fn new() -> Self {
        ActorProgression {
            xp: 0,
            level: 1,
            skill_points: 0,
            skill_levels: BTreeMap::new(),
            marks: Vec::new(),
            way: None,
            passives: BTreeSet::new(),
            abilities: BTreeSet::new(),
            effect_values: BTreeMap::new(),
        }
    }

    /// Create a progression state for an actor initialized at a given level.
    /// Used when pre-generating NPCs who start at a higher level.
    pub fn at_level(level: u32) -> Self {
        let xp = xp_for_level(level);
        let skill_points = (level - 1) * SKILL_POINTS_PER_LEVEL;
        let _marks = marks_earned_by_level(level);
        // We track marks by count but don't assign specific ones automatically.
        ActorProgression {
            xp,
            level,
            skill_points,
            skill_levels: BTreeMap::new(),
            marks: Vec::new(),
            way: None,
            passives: BTreeSet::new(),
            abilities: BTreeSet::new(),
            effect_values: BTreeMap::new(),
        }
    }

    /// Get the skill level for a given skill line (returns 0 if untrained).
    pub fn skill_level(&self, skill: SkillLine) -> u32 {
        self.skill_levels.get(&skill).copied().unwrap_or(0)
    }

    /// Spend one skill point to increase a skill line by one level.
    ///
    /// Returns `Ok(())` on success, or an error string describing the problem.
    pub fn spend_skill_point(&mut self, skill: SkillLine) -> Result<u32, &'static str> {
        if self.skill_points == 0 {
            return Err("no skill points available");
        }
        let current = self.skill_level(skill);
        if current >= SkillLine::MAX_LEVEL {
            return Err("skill is already at maximum level");
        }
        self.skill_points -= 1;
        let new_level = current + 1;
        self.skill_levels.insert(skill, new_level);
        Ok(new_level)
    }

    /// Add a Mark string ID to this actor's acquired marks.
    pub fn add_mark(&mut self, mark_id: &str) -> Result<(), &'static str> {
        if self.marks.len() >= marks_earned_by_level(self.level) as usize {
            return Err("no mark slots available at current level");
        }
        if self.marks.contains(&mark_id.to_string()) {
            return Err("mark already acquired");
        }
        self.marks.push(mark_id.to_string());
        Ok(())
    }

    /// Set the Way (trait) for this actor. Can only be set once.
    pub fn set_way(&mut self, way_id: &str) -> Result<(), &'static str> {
        if self.way.is_some() {
            return Err("way already set");
        }
        self.way = Some(way_id.to_string());
        Ok(())
    }

    pub fn has_passive(&self, passive: &str) -> bool {
        self.passives.contains(passive)
    }

    pub fn has_ability(&self, ability: &str) -> bool {
        self.abilities.contains(ability)
    }

    pub fn effect_value(&self, key: &str) -> i32 {
        self.effect_values.get(key).copied().unwrap_or(0)
    }
}

impl Default for ActorProgression {
    fn default() -> Self {
        Self::new()
    }
}

/// The result of awarding XP to an actor.
#[derive(Debug, Clone)]
pub struct XpAwardResult {
    /// Events generated by the XP award and any resulting level-ups.
    pub events: Vec<Event>,
    /// Whether the actor gained one or more levels.
    pub levelled_up: bool,
    /// The actor's new level after the award.
    pub new_level: u32,
    /// Number of new marks gained (to be chosen later).
    pub new_marks: u32,
}

/// Award XP to an actor and process any resulting level-ups.
///
/// Returns the events generated and a summary of what happened.
pub fn award_xp(
    actor_id: ActorId,
    progression: &mut ActorProgression,
    xp_amount: u64,
) -> XpAwardResult {
    let mut events = Vec::new();
    let _old_level = progression.level;

    progression.xp += xp_amount;

    // Check for level-ups
    let mut new_marks = 0u32;
    let mut levelled_up = false;

    while let Some(new_level) = check_level_up(progression.level, progression.xp) {
        levelled_up = true;
        let _old_level_before = progression.level;
        progression.level = new_level;
        progression.skill_points += SKILL_POINTS_PER_LEVEL;

        // Check if this level grants a Mark
        if level_grants_mark(new_level) {
            new_marks += 1;
        }

        events.push(Event::LevelUp {
            actor: actor_id,
            new_level,
            skill_points_granted: SKILL_POINTS_PER_LEVEL,
            marks_granted: if level_grants_mark(new_level) { 1 } else { 0 },
        });
    }

    events.push(Event::XpGained {
        actor: actor_id,
        xp: xp_amount,
        total_xp: progression.xp,
        new_level: if levelled_up {
            Some(progression.level)
        } else {
            None
        },
    });

    XpAwardResult {
        events,
        levelled_up,
        new_level: progression.level,
        new_marks,
    }
}

/// Compute the combat bonuses an actor gets from their skill levels.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SkillBonuses {
    pub pistols_accuracy: i32,
    pub long_guns_accuracy: i32,
    pub scatterguns_accuracy: i32,
    pub blades_accuracy: i32,
    pub explosives_accuracy: i32,
    pub medicine_heal_bonus: i32,
    pub scouting_sight_bonus: i32,
    pub talk_bonus: i32,
}

/// Derive all skill-based combat bonuses from an actor's progression.
pub fn compute_skill_bonuses(prog: &ActorProgression) -> SkillBonuses {
    SkillBonuses {
        pistols_accuracy: pb_core::progression::skill_accuracy_bonus(
            prog.skill_level(SkillLine::Pistols),
        ),
        long_guns_accuracy: pb_core::progression::skill_accuracy_bonus(
            prog.skill_level(SkillLine::LongGuns),
        ),
        scatterguns_accuracy: pb_core::progression::skill_accuracy_bonus(
            prog.skill_level(SkillLine::Scatterguns),
        ),
        blades_accuracy: pb_core::progression::skill_accuracy_bonus(
            prog.skill_level(SkillLine::Blades),
        ),
        explosives_accuracy: pb_core::progression::skill_accuracy_bonus(
            prog.skill_level(SkillLine::Explosives),
        ),
        medicine_heal_bonus: pb_core::progression::medicine_heal_bonus(
            prog.skill_level(SkillLine::FieldMedicine),
        ),
        scouting_sight_bonus: pb_core::progression::scouting_sight_bonus(
            prog.skill_level(SkillLine::Scouting),
        ),
        talk_bonus: prog.skill_level(SkillLine::Talk) as i32,
    }
}

/// Calculate the total XP award for completing a scenario.
///
/// Base + objective bonuses + casualties penalty applied by caller.
pub fn scenario_xp_award(
    primary_objectives_completed: u32,
    bonus_objectives_completed: u32,
    headshot_kills: u32,
    no_casualties: bool,
) -> u64 {
    let mut xp = BASE_SCENARIO_XP;
    xp += primary_objectives_completed as u64 * OBJECTIVE_BONUS_XP;
    xp += bonus_objectives_completed as u64 * BONUS_OBJECTIVE_XP;
    xp += headshot_kills as u64 * HEADSHOT_BONUS_XP;
    if no_casualties {
        xp += NO_CASUALTIES_BONUS_XP;
    }
    xp
}

#[cfg(test)]
mod tests {
    use super::*;
    use pb_core::ids::ActorId;

    #[test]
    fn new_progression_is_level_1() {
        let prog = ActorProgression::new();
        assert_eq!(prog.level, 1);
        assert_eq!(prog.xp, 0);
        assert_eq!(prog.skill_points, 0);
    }

    #[test]
    fn at_level_5_has_correct_xp_and_points() {
        let prog = ActorProgression::at_level(5);
        assert_eq!(prog.level, 5);
        assert_eq!(prog.xp, 1000);
        assert_eq!(prog.skill_points, 4);
        // Higher-level actors have an earned slot, but marks require an
        // explicit content-backed choice and are never fabricated here.
        assert_eq!(marks_earned_by_level(prog.level), 1);
        assert!(prog.marks.is_empty());
    }

    #[test]
    fn spend_skill_point_increases_skill() {
        let mut progression = ActorProgression::at_level(3);
        let points_before = progression.skill_points;
        let result = progression.spend_skill_point(SkillLine::Pistols);
        assert_eq!(result, Ok(1));
        assert_eq!(progression.skill_points, points_before - 1);
        assert_eq!(progression.skill_level(SkillLine::Pistols), 1);
    }

    #[test]
    fn spend_skill_point_fails_when_none_available() {
        let mut prog = ActorProgression::new();
        let result = prog.spend_skill_point(SkillLine::Pistols);
        assert!(result.is_err());
    }

    #[test]
    fn spend_skill_point_fails_at_max() {
        let mut prog = ActorProgression::new();
        prog.skill_points = 10;
        // Level up to max
        for _ in 0..SkillLine::MAX_LEVEL {
            let _ = prog.spend_skill_point(SkillLine::Pistols);
        }
        let result = prog.spend_skill_point(SkillLine::Pistols);
        assert!(result.is_err());
    }

    #[test]
    fn add_mark_adds_to_list() {
        let mut prog = ActorProgression::at_level(3); // 1 mark slot
        assert!(prog.add_mark("mk_steady_hands").is_ok());
        assert_eq!(prog.marks.len(), 1);
        assert_eq!(prog.marks[0], "mk_steady_hands");
    }

    #[test]
    fn add_mark_fails_duplicate() {
        let mut prog = ActorProgression::at_level(3);
        assert!(prog.add_mark("mk_steady_hands").is_ok());
        assert!(prog.add_mark("mk_steady_hands").is_err());
    }

    #[test]
    fn set_way_sets_value() {
        let mut prog = ActorProgression::new();
        assert!(prog.set_way("wy_old_wound").is_ok());
        assert_eq!(prog.way, Some("wy_old_wound".to_string()));
    }

    #[test]
    fn set_way_fails_twice() {
        let mut prog = ActorProgression::new();
        assert!(prog.set_way("wy_old_wound").is_ok());
        assert!(prog.set_way("wy_quick_and_loud").is_err());
        assert_eq!(prog.way, Some("wy_old_wound".to_string()));
    }

    #[test]
    fn award_xp_basic() {
        let mut prog = ActorProgression::new();
        let result = award_xp(ActorId(1), &mut prog, 100);
        assert!(result.levelled_up);
        assert_eq!(result.new_level, 2);
        assert_eq!(prog.level, 2);
        assert_eq!(prog.xp, 100);
        assert_eq!(prog.skill_points, 1);
    }

    #[test]
    fn award_xp_no_level_up() {
        let mut prog = ActorProgression::new();
        let result = award_xp(ActorId(1), &mut prog, 50);
        assert!(!result.levelled_up);
        assert_eq!(prog.level, 1);
        assert_eq!(prog.xp, 50);
        assert_eq!(prog.skill_points, 0);
    }

    #[test]
    fn award_xp_multi_level_up() {
        let mut prog = ActorProgression::new();
        // 600 XP should take us from level 1 to level 4
        let result = award_xp(ActorId(1), &mut prog, 600);
        assert!(result.levelled_up);
        assert_eq!(prog.level, 4);
        assert_eq!(prog.xp, 600);
        // Should have gained 3 skill points (1 each for levels 2, 3, 4)
        assert_eq!(prog.skill_points, 3);
        // Level 3 grants a mark
        assert_eq!(result.new_marks, 1);
    }

    #[test]
    fn award_xp_grant_mark_at_level_3() {
        let mut progression = ActorProgression::at_level(2);
        progression.xp = 99;
        progression.skill_points = 1;
        let result = award_xp(ActorId(1), &mut progression, 201);
        assert!(result.levelled_up);
        assert_eq!(progression.level, 3);
        assert_eq!(result.new_marks, 1);
    }

    #[test]
    fn award_xp_no_mark_for_level_2() {
        let mut prog = ActorProgression::new();
        let result = award_xp(ActorId(1), &mut prog, 100);
        assert!(result.levelled_up);
        assert_eq!(result.new_marks, 0);
    }

    #[test]
    fn compute_skill_bonuses_untrained() {
        let prog = ActorProgression::new();
        let bonuses = compute_skill_bonuses(&prog);
        assert_eq!(bonuses.pistols_accuracy, 0);
        assert_eq!(bonuses.long_guns_accuracy, 0);
        assert_eq!(bonuses.medicine_heal_bonus, 0);
    }

    #[test]
    fn compute_skill_bonuses_trained() {
        let mut prog = ActorProgression::new();
        prog.skill_points = 5;
        let _ = prog.spend_skill_point(SkillLine::Pistols);
        let _ = prog.spend_skill_point(SkillLine::Pistols);
        let _ = prog.spend_skill_point(SkillLine::LongGuns);
        let _ = prog.spend_skill_point(SkillLine::FieldMedicine);
        let _ = prog.spend_skill_point(SkillLine::Scouting);

        let bonuses = compute_skill_bonuses(&prog);
        assert_eq!(bonuses.pistols_accuracy, 2);
        assert_eq!(bonuses.long_guns_accuracy, 1);
        assert_eq!(bonuses.medicine_heal_bonus, 1);
        assert_eq!(bonuses.scouting_sight_bonus, 1);
    }

    #[test]
    fn scenario_xp_award_default() {
        let xp = scenario_xp_award(0, 0, 0, false);
        assert_eq!(xp, BASE_SCENARIO_XP);
    }

    #[test]
    fn scenario_xp_award_full() {
        let xp = scenario_xp_award(1, 1, 3, true);
        let expected = BASE_SCENARIO_XP
            + OBJECTIVE_BONUS_XP
            + BONUS_OBJECTIVE_XP
            + 3 * HEADSHOT_BONUS_XP
            + NO_CASUALTIES_BONUS_XP;
        assert_eq!(xp, expected);
    }

    #[test]
    fn events_award_xp_generates_xp_gained() {
        let mut prog = ActorProgression::new();
        let result = award_xp(ActorId(1), &mut prog, 50);
        let xp_events: Vec<&Event> = result
            .events
            .iter()
            .filter(|e| matches!(e, Event::XpGained { .. }))
            .collect();
        assert_eq!(xp_events.len(), 1);
    }

    #[test]
    fn events_award_xp_level_up_includes_level_up_events() {
        let mut prog = ActorProgression::new();
        let result = award_xp(ActorId(1), &mut prog, 300);
        let level_up_events: Vec<&Event> = result
            .events
            .iter()
            .filter(|e| matches!(e, Event::LevelUp { .. }))
            .collect();
        // Should have level-up events for levels 2 and 3
        assert_eq!(level_up_events.len(), 2);
    }
}
